export const GET_ECONOMY_LIST_START = 'GET_ECONOMY_LIST_START';
export const GET_ECONOMY_LIST_SUCCESS = 'GET_ECONOMY_LIST_SUCCESS';
export const GET_ECONOMY_LOADING_FAIL = 'GET_ECONOMY_LOADING_FAIL';

export const CREATE_ECONOMY_LIST = 'CREATE_ECONOMY_LIST';
export const REMOVE_ECONOMY_LIST = 'REMOVE_ECONOMY_LIST';
export const UPDATE_ECONOMY_LIST = 'UPDATE_ECONOMY_LIST';
